const FACESET = {
  ":happy:": "😊",
  ":sad:": "😞",
  ":crying:": "😭",
  ":puke:": "🤢",
  ":cool:": "😎",
  ":laugh:": "😆",
  ":sun:": "☀️",
  ":heart:": "❤️",
  ":sing:": "🎤",
  ":crylaugh:": "😂",
  ":thumbsup:": "👍",
  ":sob:": "😭",
  ":inlove:": "🥰",
  ":hearteyes:": "😍",
  ":blush:": "😳",
  ":party:": "🎉",
  ":fire:": "🔥",
  ":annoyed:": "🙄",
  ":wink:": "😉",
  ":bday:": "🎂",
  ":clap:": "👏",
  ":star:": "✨",
  ":rose:": "🌹",
  ":flower:": "🌻",
  ":crazy:": "🤪",
  ":skull:": "💀",
  ":money:": "💰",
  ":gift:": "🎁",
  ":java:": "☕",
  ":butterfly:": "🦋",
  ":lucky:": "🍀"
}

export default FACESET;