const FACESET = {
  ":happy:": "/faces/retro/happy.gif",
  ":sad:": "/faces/retro/sad.gif",
  ":crying:": "/faces/retro/crying.gif",
  ":puke:": "/faces/retro/puke.gif",
  ":cool:": "/faces/retro/cool.gif",
  ":laugh:": "/faces/retro/laugh.gif",
  ":sun:": "/faces/retro/sun.png",
  ":heart:": "/faces/retro/heart.gif",
  ":sing:": "/faces/retro/singer.gif",
  ":crylaugh:": "/faces/retro/crylaugh.gif",
  ":thumbsup:": "/faces/retro/thumbsup.gif",
  ":thumbsdown:": "/faces/retro/thumbsdown.gif",
  ":sob:": "/faces/retro/sob.gif",
  ":inlove:": "/faces/retro/inlove.gif",
  ":hearteyes:": "/faces/retro/hearteyes.gif",
  ":kiss:": "/faces/retro/kiss.gif",
  ":blush:": "/faces/retro/blush.gif",
  ":party:": "/faces/retro/party.gif",
  ":fire:": "/faces/retro/fire.gif",
  ":annoyed:": "/faces/retro/annoyed.gif",
  ":wink:": "/faces/retro/wink.gif",
  ":bday:": "/faces/retro/birthday.gif",
  ":clap:": "/faces/retro/clap.gif",
  ":star:": "/faces/retro/star.gif",
  ":rose:": "/faces/retro/rose.gif",
  ":flower:": "/faces/retro/flower.gif",
  ":crazy:": "/faces/retro/crazy.gif",
  ":skull:": "/faces/retro/skull.gif",
  ":smirk:": "/faces/retro/smirk.gif",
  // ":java:": "/faces/retro/java.gif",
  // ":butterfly:": "/faces/retro/butterfly.gif",
  // ":lucky:": "/faces/retro/lucky.gif",
}

export default FACESET;